version: '3.9'

services:

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: app
    command: >
      bash -c "
        gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main:app --bind 0.0.0.0:8000
            "
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - ./src:/src/
      - ./alembic:/alembic/
    depends_on:
      - prod-db
      - redis
    restart: always
    networks:
      - web-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl-tutorials.key:/etc/ssl/ssl-tutorials.key
      - ./nginx/ssl-bundle.crt:/etc/ssl/ssl-bundle.crt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always
    networks:
      - web-network

  redis_listener:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: redis_listener
    command: python ./src/consumer.py
    environment:
      - PYTHONPATH=.
    env_file:
      - ./.env
    volumes:
      - ./src:/src/
    depends_on:
      - redis
      - prod-db
      - app
    restart: always
    networks:
      - web-network

  prod-db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - proddb-volume:/var/lib/postgresql/data
    networks:
      - web-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --notify-keyspace-events Kx
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    restart: always
    networks:
      - web-network

name: smart-process-deplyment
volumes:
  proddb-volume:
  redis-volume:
networks:
  web-network:
