version: '3.9'

services:

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: app
    command: >
      sh -c "
            uvicorn src.main:app --host=0.0.0.0 --reload
            alembic revision --autogenerate -m "init"
            alembic upgrade head
          "
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    volumes:
      - ./src:/src/
      - ./alembic:/alembic/
    depends_on:
      - dev-db
      - redis
    restart: always

  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - devdb-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:7.2-alpine    
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data


name: smart-process
volumes:
  devdb-volume:
  redis-volume:
