FROM python:3.12-bullseye
LABEL maintainer="mrrahbarnia@gmail.com"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements/base.txt /tmp/base.txt
COPY ./requirements/local.txt /tmp/local.txt
COPY . .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/base.txt

RUN apt-get update && \
    apt-get install -y gcc libpq-dev curl && \
    apt clean && \
    rm -rf /tmp
