"""init

Revision ID: 8a8c3d2e1eb0
Revises: 1d82635ea530
Create Date: 2024-10-27 18:19:39.996426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8c3d2e1eb0'
down_revision: Union[str, None] = '1d82635ea530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_articles_title'), 'articles', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_articles_title'), 'articles', type_='unique')
    # ### end Alembic commands ###
